
// Auto-imported equipment data
const importedEquipment = [
  {
    "id": 1,
    "equipmentId": "EQ10001",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "VVFE42FF1X",
    "serialNumber": "89423280I",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FABIO PASSARI",
    "notes": "Setor: T.I | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-10210U / 16GB"
  },
  {
    "id": 2,
    "equipmentId": "EQ10002",
    "name": "MONITOR LG 23,8",
    "category": "monitor",
    "model": "24MK430H-B",
    "serialNumber": "211AZRD9Q110",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FABIO PASSARI",
    "notes": "Setor: T.I | Acessórios: FONTE ALIMENTACAO "
  },
  {
    "id": 3,
    "equipmentId": "EQ10003",
    "name": "NB DELL",
    "category": "notebook",
    "model": "VOSTRO 15 3510",
    "serialNumber": "76HY8X3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "GABRIELE STOKINGER",
    "notes": "Setor: FINANCEIRO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I7-1165G7  / 16GB"
  },
  {
    "id": 4,
    "equipmentId": "EQ10004",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "P112FN",
    "serialNumber": "64UUGH3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "GABRIELE STOKINGER",
    "notes": "Setor: FINANCEIRO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 5,
    "equipmentId": "EQ10005",
    "name": "ALL IN ONE DELL",
    "category": "desktop",
    "model": "W12C",
    "serialNumber": "5DZT0L2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "GENIFER ",
    "notes": "Setor: FINANCEIRO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO"
  },
  {
    "id": 6,
    "equipmentId": "EQ10006",
    "name": "MINI PC DELL ",
    "category": "desktop",
    "model": "D10V",
    "serialNumber": "270KQX2",
    "status": "assigned",
    "location": "Faz. NSA",
    "assignedTo": "MARCIELLI",
    "notes": "Setor: ADMINSTRATIVO | Acessórios: FONTE ALIMENTAÇÃO TECLADO E MOUSE "
  },
  {
    "id": 7,
    "equipmentId": "EQ10007",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "SE2416H",
    "serialNumber": "S/N",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ISABELE",
    "notes": "Setor: FINANCEIRO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 8,
    "equipmentId": "EQ10008",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "P2422HB",
    "serialNumber": "BR-094DT7",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ANA ",
    "notes": "Setor: FINANCEIRO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 9,
    "equipmentId": "EQ10009",
    "name": "MINI PC DELL ",
    "category": "desktop",
    "model": "D14U",
    "serialNumber": "34PY8K3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ANA",
    "notes": "Setor: FINANCEIRO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5 10500T/ 8GB"
  },
  {
    "id": 10,
    "equipmentId": "EQ10010",
    "name": "CELULAR MOTOROLA E22",
    "category": "mobile",
    "model": "PAVU0007BR",
    "serialNumber": "UI5HVC3STR",
    "status": "assigned",
    "location": "Cotton",
    "assignedTo": "KISMAR MOURA",
    "notes": "Setor: ALGODOEIRA | Acessórios: CARREGADOR, CABO USB, CHAVE REMOÇÃO CHIP | Obs: IMEI:355165982083257/352165982083265"
  },
  {
    "id": 11,
    "equipmentId": "EQ10011",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "VJF155F11X",
    "serialNumber": "89260021E",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "JOSUE",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO"
  },
  {
    "id": 12,
    "equipmentId": "EQ10012",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "E2222HS",
    "serialNumber": "BR-04VR43-TUB00-IBF-4E3U-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "JOSUE",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 13,
    "equipmentId": "EQ10013",
    "name": "NB DELL",
    "category": "notebook",
    "model": "P6EF",
    "serialNumber": "0JWF6A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "LUCAS GONCALVES",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I7-7500U/8GB"
  },
  {
    "id": 14,
    "equipmentId": "EQ10014",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "E2222HS",
    "serialNumber": "BR-04VR43-TUB00-IBF-4F0U-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "LUCAS GONCALVES",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 15,
    "equipmentId": "EQ10015",
    "name": "NB DELL",
    "category": "notebook",
    "model": "P10015",
    "serialNumber": "35XHYR2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ELCIANE",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-7200U/8GB"
  },
  {
    "id": 16,
    "equipmentId": "EQ10016",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "E2222HS",
    "serialNumber": "BR-04VR43-TUB00-IBF-OB9Z-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "PATRICIA",
    "notes": "Setor: FISCAL | Acessórios: FONTE DE ALIMENTACAO"
  },
  {
    "id": 17,
    "equipmentId": "EQ10017",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "E2222HS",
    "serialNumber": "BR-04VR43-TUB00-IBF-25D-441Z-A02",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RENATO",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE DE ALIMENTACAO"
  },
  {
    "id": 18,
    "equipmentId": "EQ10018",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE15",
    "serialNumber": "87080270U",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "LUCAS",
    "notes": "Setor: FISCAL | Acessórios: FONTE DE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1015U-8gb"
  },
  {
    "id": 19,
    "equipmentId": "EQ10019",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "P2719H",
    "serialNumber": "BR-OP2TRT-TUB00-1A5-40UB-AI3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "CLEIDIANARA",
    "notes": "Setor: FISCAL | Acessórios: FONTE DE ALIMENTACAO"
  },
  {
    "id": 20,
    "equipmentId": "EQ10020",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": 894415550,
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "LUCILA",
    "notes": "Setor: FISCAL | Acessórios: FONTE DE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1021U/8GB"
  },
  {
    "id": 21,
    "equipmentId": "EQ10021",
    "name": "MONITOR LG 23,8",
    "category": "monitor",
    "model": "20MR400H-B",
    "serialNumber": "1048PRW0F758",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "HOTUSZIEL",
    "notes": "Setor: FISCAL | Acessórios: FONTE DE ALIMENTACAO"
  },
  {
    "id": 22,
    "equipmentId": "EQ10022",
    "name": "NB DELL",
    "category": "notebook",
    "model": "INSPIRION 15",
    "serialNumber": "3DBV9X2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "HOTUSZIEL",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-7200U/8GB"
  },
  {
    "id": 23,
    "equipmentId": "EQ10023",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": "89423153R",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DOUGLAS",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1021U/8GB"
  },
  {
    "id": 24,
    "equipmentId": "EQ10024",
    "name": "MONITOR LG 23,8",
    "category": "monitor",
    "model": "24MK430H-B",
    "serialNumber": "211AZ6F4H151",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DOUGLAS",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 25,
    "equipmentId": "EQ10025",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE15",
    "serialNumber": 870803582,
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RENATA",
    "notes": "Setor: COMERCIAL | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I7-1051U/8GB"
  },
  {
    "id": 26,
    "equipmentId": "EQ10026",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": 89420714,
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DISPONIVEL",
    "notes": "Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1021U/8GB"
  },
  {
    "id": 27,
    "equipmentId": "EQ10027",
    "name": "GALAXY TAB A7",
    "category": "other",
    "model": "SM-T500",
    "serialNumber": "R9XRA0362JT",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DOUGLAS",
    "notes": "Setor: PRODUCAO | Acessórios: CARREGADO,CABO USB"
  },
  {
    "id": 28,
    "equipmentId": "EQ10029",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "P2422HB",
    "serialNumber": "BR-067NW4-TU800-198-BV0L-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FERNANDO VIEIRA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 29,
    "equipmentId": "EQ10030",
    "name": "NB DELL",
    "category": "notebook",
    "model": "INSPIRION 15",
    "serialNumber": "F7333T2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ANDREINA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO"
  },
  {
    "id": 30,
    "equipmentId": "EQ10031",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "SE22222H",
    "serialNumber": "BR-0RK34N-TUB00-28H-SN31-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "JEDSON LIMA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO "
  },
  {
    "id": 31,
    "equipmentId": "EQ10032",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "SE22222H",
    "serialNumber": "BR-0RK34N-TV800-28H-SN11-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "IBERE",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 32,
    "equipmentId": "EQ10033",
    "name": "NB ACER NITRO5",
    "category": "notebook",
    "model": "NITRO5",
    "serialNumber": "NHQRAL0050300D3749501",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RENATO",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: RYZEN5 3550H/24GB"
  },
  {
    "id": 33,
    "equipmentId": "EQ10034",
    "name": "NB LENOVO IDEAPAD GAMING3I",
    "category": "notebook",
    "model": "GAMINGI3",
    "serialNumber": "PEOA1P",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "LARISSA",
    "notes": "Setor: MARKETING | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-11300H/8GB"
  },
  {
    "id": 34,
    "equipmentId": "EQ10036",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": "89423146D",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FLAVIA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-10210U/8GB"
  },
  {
    "id": 35,
    "equipmentId": "EQ10037",
    "name": "MONITOR DELL",
    "category": "monitor",
    "model": "P19135B",
    "serialNumber": "CN-07CT16-74261-332-0AUU",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FLAVIA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 36,
    "equipmentId": "EQ10038",
    "name": "MONITOR LG",
    "category": "monitor",
    "model": "20MK400H-B",
    "serialNumber": "1054PRW0C102",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "MONICA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 37,
    "equipmentId": "EQ10039",
    "name": "NB DELL",
    "category": "notebook",
    "model": "VOSTRO 15 3515",
    "serialNumber": "60JTJM3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "MONICA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: RYZEN 5 3450U/24GB"
  },
  {
    "id": 38,
    "equipmentId": "EQ10040",
    "name": "TV LG 55",
    "category": "other",
    "model": "SSUN731C0SC",
    "serialNumber": "011AZTN6K089",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "SALINHA REUNIAO",
    "notes": "Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 39,
    "equipmentId": "EQ10042",
    "name": "TV LG 75",
    "category": "other",
    "model": "75UK65",
    "serialNumber": "904AZTHCD257",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "SALA REUNIAO",
    "notes": "Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 40,
    "equipmentId": "EQ10043",
    "name": "COMPUTADOR SALA DE REUNIÃO",
    "category": "other",
    "model": "Modelo não informado",
    "serialNumber": "S/N",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "SALA REUNIAO",
    "notes": "Acessórios: FONTE DE ALIMENTACAO"
  },
  {
    "id": 41,
    "equipmentId": "EQ10045",
    "name": "TELEFONE GRANDSTREAM",
    "category": "other",
    "model": "GXP1610",
    "serialNumber": "24ML3MN108435CB",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DAINA",
    "notes": "Setor: RECEPCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 42,
    "equipmentId": "EQ10046",
    "name": "ALL IN ONE DELL",
    "category": "desktop",
    "model": "W12C",
    "serialNumber": "5F0L0L2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DAINA",
    "notes": "Setor: RECEPCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-7200U/8GB"
  },
  {
    "id": 43,
    "equipmentId": "EQ10047",
    "name": "CELULAR GALAXY A32",
    "category": "mobile",
    "model": "GALAXY A32",
    "serialNumber": "RQ8T307N4LE",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DAINA",
    "notes": "Setor: RECEPCAO | Acessórios: CARREGADOR | Obs: 350784348503314/352189678503314"
  },
  {
    "id": 44,
    "equipmentId": "EQ10049",
    "name": "NB DELL",
    "category": "notebook",
    "model": "VOSTRO3520",
    "serialNumber": "3L046V3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "JEDSON LIMA",
    "notes": "Setor: DEPARTAMENTO PRODUÇÃO  | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I7-1255U  / 16GB"
  },
  {
    "id": 45,
    "equipmentId": "EQ10051",
    "name": "NB DELL ",
    "category": "notebook",
    "model": "P112FN",
    "serialNumber": "B9HY8X3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FERNANDO VIEIRA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO | Obs: I7-1165G7  / 16GB"
  },
  {
    "id": 46,
    "equipmentId": "EQ10052",
    "name": "NB ACER NITRO 5",
    "category": "notebook",
    "model": "NITRO5",
    "serialNumber": "NHQ9RAL0020412A5589501",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DOUGLAS",
    "notes": "Setor: T.I | Acessórios: FONTE ALIMENTACAO | Obs: RYZEN 7 3750H/16GB"
  },
  {
    "id": 47,
    "equipmentId": "EQ10053",
    "name": "MONITOR LG 23,8",
    "category": "monitor",
    "model": "24MK430H-B",
    "serialNumber": "211AZXC4H258",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DOUGLAS",
    "notes": "Setor: T.I | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 48,
    "equipmentId": "EQ10054",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "NIE09BG",
    "serialNumber": "8553D20E9177",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "CLEIDIANARA",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-10210U / 8GB"
  },
  {
    "id": 49,
    "equipmentId": "EQ10055",
    "name": "NB DELL",
    "category": "notebook",
    "model": "P75F006",
    "serialNumber": "20C9703",
    "status": "assigned",
    "location": "ARMAZEM PA",
    "assignedTo": "ELVIZ",
    "notes": "Acessórios: FONTE ALIMENTACAO | Obs: i5-8265u/8gb"
  },
  {
    "id": 50,
    "equipmentId": "EQ10056",
    "name": "TELEFONE GRANDSTREAM",
    "category": "other",
    "model": "GXP1610",
    "serialNumber": "24UML3MN10843D22",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DOUGLAS",
    "notes": "Setor: T.I | Acessórios: FONTE ALIENTACAO"
  },
  {
    "id": 51,
    "equipmentId": "EQ10059",
    "name": "TELEVISÃO LG ",
    "category": "other",
    "model": "50UP751C0SF.BWZJLJZ",
    "serialNumber": "108AZMG49995",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ESCRITORIO MATRIZ",
    "notes": "Setor: LOGISTICA | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 52,
    "equipmentId": "EQ10060",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "SE22222H",
    "serialNumber": "BR-04VR43TVB00-239-OCBU-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "GIOVAN",
    "notes": "Setor: LOGISTICA | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 53,
    "equipmentId": "EQ10061",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "SE22222H",
    "serialNumber": "BR-04VR43TVB00-239-OCBU-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FABRICIO",
    "notes": "Setor: LOGISTICA | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 54,
    "equipmentId": "EQ10062",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "SE22222H",
    "serialNumber": "BR-04VR43-TV800-239-0DAU-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "KEROLLAYNNE",
    "notes": "Setor: TRANSPORTADORA | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 55,
    "equipmentId": "EQ10063",
    "name": "CELULAR MOTOROLA G22",
    "category": "mobile",
    "model": "MOTO G22",
    "serialNumber": "IHDT56AC2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "GENIFFER",
    "notes": "Setor: FINANCEIRO | Acessórios: CARREGADOR | Obs: 358946838284356/358946838284364"
  },
  {
    "id": 56,
    "equipmentId": "EQ10064",
    "name": "CELULAR GALAXY A32",
    "category": "mobile",
    "model": "SM-A32M/DS",
    "serialNumber": "RQ8T307N4TZ",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "CLEIDIANARA",
    "notes": "Setor: FISCAL | Acessórios: CARREGADOR | Obs: 350784348503389/352189678503389"
  },
  {
    "id": 57,
    "equipmentId": "EQ10065",
    "name": "TELEVISÃO LG ",
    "category": "other",
    "model": "50UP751C0SF.BWZJLJZ",
    "serialNumber": "108AZZX2U285",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ESCRITORIO MATRIZ",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 58,
    "equipmentId": "EQ10066",
    "name": "CELULAR MOTOROLA E22",
    "category": "mobile",
    "model": "Modelo não informado",
    "serialNumber": "UI5HVC3RMR",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "THAYS DE PARIS",
    "notes": "Setor: RH | Acessórios: CARREGADOR | Obs: 35516598069876/355165982069884"
  },
  {
    "id": 59,
    "equipmentId": "EQ10067",
    "name": "NB DELL",
    "category": "notebook",
    "model": "DELL G15 5515",
    "serialNumber": "G3M5YLE",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "CAIO BERNARDI",
    "notes": "Setor: FISCAL | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: AMD RYZEN 5 5600H / 24GB"
  },
  {
    "id": 60,
    "equipmentId": "EQ10068",
    "name": "NB DELL",
    "category": "notebook",
    "model": "VOSTRO 15 3515",
    "serialNumber": "76ZNGR3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ALEX PRATES",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: IAMD Ryzen 7 3700U  / 24 GB"
  },
  {
    "id": 61,
    "equipmentId": "EQ10069",
    "name": "CELULAR MOTOROLA G20",
    "category": "mobile",
    "model": "MOTOG20",
    "serialNumber": "RTAS3168663",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "CLEIDIANARA",
    "notes": "Setor: FISCAL | Acessórios: CARREGADOR | Obs: 354494571499893/354494571499901"
  },
  {
    "id": 62,
    "equipmentId": "EQ10070",
    "name": "CELULAR GALAXY A32",
    "category": "mobile",
    "model": "SM-A325M/DS",
    "serialNumber": "RQ8R906C8GV",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "CAIO BERNARDI",
    "notes": "Setor: FISCAL | Acessórios: CARREGADOR | Obs: 350784343825530/352189673825530"
  },
  {
    "id": 63,
    "equipmentId": "EQ10071",
    "name": "NB DELL",
    "category": "notebook",
    "model": "VOSTRO 3520",
    "serialNumber": "U7ILUIO",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "IBERE",
    "notes": "Setor: PRODUCAO | Acessórios: CARREGADOR | Obs: I7-1255U / 16 GB"
  },
  {
    "id": 64,
    "equipmentId": "EQ10072",
    "name": "CELULAR GALAXY A12",
    "category": "mobile",
    "model": "SM-A125M",
    "serialNumber": "RQ8NC03X0VM",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RENATA",
    "notes": "Setor: COMERCIAL | Acessórios: CARREGADOR | Obs: 356707180045213/357746770045216"
  },
  {
    "id": 65,
    "equipmentId": "EQ10073",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "VJFE42F11X-B0352H",
    "serialNumber": "7EC3F92F504",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "LEANDRO MIRA",
    "notes": "Setor: PRODUCAO | Acessórios: CARREGADOR | Obs: I5-10210U / 8 GB"
  },
  {
    "id": 66,
    "equipmentId": "EQ10074",
    "name": "CELULAR MOTOROLA E32",
    "category": "mobile",
    "model": "MOTO E32",
    "serialNumber": "ROR3133528",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ALEX PRATES",
    "notes": "Setor: PRODUCAO | Acessórios: CARREGADOR | Obs: 353150461127959/353150461127967"
  },
  {
    "id": 67,
    "equipmentId": "EQ10075",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "P2719H",
    "serialNumber": "BR-OP2TRT-TUB00-1A5-40UB-AI3",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ELIZANGELA",
    "notes": "Setor: TRANSPORTADORA | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 68,
    "equipmentId": "EQ10076",
    "name": "TELEFONE GRANDSTREAM",
    "category": "other",
    "model": "GXP1610",
    "serialNumber": "24UML3MN108435B5",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ELIZANGELA",
    "notes": "Setor: TRANSPORTADORA | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 69,
    "equipmentId": "EQ10077",
    "name": "CELULAR GALAXY A32",
    "category": "mobile",
    "model": "SM-A325M/DS",
    "serialNumber": "RQ8R90AJ8EL",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "ELIZANGELA",
    "notes": "Setor: TRANSPORTADORA | Acessórios: CARREGADOR | Obs: 35078344180851/352189674180851"
  },
  {
    "id": 70,
    "equipmentId": "EQ10078",
    "name": "MINI PC DELL ",
    "category": "desktop",
    "model": "24PY8K3",
    "serialNumber": 4639017171,
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "PATRICQ",
    "notes": "Setor: TRANSPORTADORA | Acessórios: FONTE ALIMENTACAO | Obs: I5-10210U/8GB"
  },
  {
    "id": 71,
    "equipmentId": "EQ10079",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "P2422HB",
    "serialNumber": "BR-094DT7-TVB00-19S-0SPL-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "PATRICQ",
    "notes": "Setor: TRANSPORTADORA | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 72,
    "equipmentId": "EQ10080",
    "name": "NB DELL",
    "category": "notebook",
    "model": "VOSTRO 3583",
    "serialNumber": 7682728395,
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "KEROLLAYNNE",
    "notes": "Setor: TRANSPORTADORA | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO  | Obs: i5-8265u/8gb"
  },
  {
    "id": 73,
    "equipmentId": "EQ10081",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": "89420724K",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "FABRICIO",
    "notes": "Setor: LOGISTICA | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-10210U/8GB"
  },
  {
    "id": 74,
    "equipmentId": "EQ10082",
    "name": "ALL IN ONE DELL",
    "category": "desktop",
    "model": "W12C",
    "serialNumber": "5DZPOL2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "MICAEL",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO  | Obs: I5-7200U/8GB"
  },
  {
    "id": 75,
    "equipmentId": "EQ10083",
    "name": "NB DELL",
    "category": "notebook",
    "model": "P75FN",
    "serialNumber": "2J3J63",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "THAYS DE PARIS",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO TECLADOE MOUSE SEM FIO "
  },
  {
    "id": 76,
    "equipmentId": "EQ10084",
    "name": "ALL IN ONE DELL",
    "category": "desktop",
    "model": "W12C",
    "serialNumber": "5DZS0L2",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "DISPONIVEL",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO  | Obs: I5-7200U/8GB"
  },
  {
    "id": 77,
    "equipmentId": "EQ10085",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "LFSVSH2",
    "serialNumber": "ORVRF7-64180-72H-OGGT-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "JOCEONE ",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO "
  },
  {
    "id": 78,
    "equipmentId": "EQ10086",
    "name": "PC DELL",
    "category": "desktop",
    "model": "VOSTRO 3470",
    "serialNumber": "1V8DWA00BH1",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "JOCEONE ",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-9400/8GB"
  },
  {
    "id": 79,
    "equipmentId": "EQ10087",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": "89420712H",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RAFAELE ",
    "notes": "Setor: RH | Acessórios: FONTE ALIMNTACAO TECLADO E MOUSE SEM FIO  | Obs: I5-10210U/8GB"
  },
  {
    "id": 80,
    "equipmentId": "EQ10088",
    "name": "MONITOR DELL 23,8",
    "category": "monitor",
    "model": "S2318H",
    "serialNumber": "CN-ORVRF7-64180-72H-113T-A00",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RAFAELE ",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO"
  },
  {
    "id": 81,
    "equipmentId": "EQ10089",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": "89423188P",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "MARIANE",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-10210U/8GB"
  },
  {
    "id": 82,
    "equipmentId": "EQ10090",
    "name": "MONITOR LG 23,8",
    "category": "monitor",
    "model": "24MK430H-B",
    "serialNumber": "211AZZX4H461",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "MARIANE",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 83,
    "equipmentId": "EQ10092",
    "name": "TELEFONE GRANDSTREAM",
    "category": "other",
    "model": "GXP1610",
    "serialNumber": "24UMN3MN10843D2B",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RH",
    "notes": "Setor: RH | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 84,
    "equipmentId": "EQ10093",
    "name": "NB DELL",
    "category": "notebook",
    "model": "P75F",
    "serialNumber": 15565197171,
    "status": "assigned",
    "location": "FAZENDA CATUAI",
    "assignedTo": "FERNANDO",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO E MOUSE SEM FIO | Obs: I5 10500T/ 24GB"
  },
  {
    "id": 85,
    "equipmentId": "EQ10094",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "VJFE42F11X",
    "serialNumber": "89420720A",
    "status": "assigned",
    "location": "FAZENDA CATUAI",
    "assignedTo": "CHARLES",
    "notes": "Setor: GERENTE FAZENDA | Acessórios: FONTE ALIMENTACAO | Obs: I5-1021U/8GB"
  },
  {
    "id": 86,
    "equipmentId": "EQ10095",
    "name": "MONITOR LG",
    "category": "monitor",
    "model": "25UM58",
    "serialNumber": "905SPAEOH500",
    "status": "assigned",
    "location": "FAZENDA CATUAI",
    "assignedTo": "PAULO",
    "notes": "Setor: ADM | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 87,
    "equipmentId": "EQ10096",
    "name": "TELEFONE GRANDSTREAM",
    "category": "other",
    "model": "962-00077-31C",
    "serialNumber": "24UML3MN10843D14",
    "status": "assigned",
    "location": "FAZENDA CATUAI",
    "assignedTo": "PAULO",
    "notes": "Setor: ADM | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 88,
    "equipmentId": "EQ10097",
    "name": "COMPUTADOR DELL",
    "category": "desktop",
    "model": "VOSTRO",
    "serialNumber": 33483850527,
    "status": "assigned",
    "location": "FAZENDA CATUAI",
    "assignedTo": "PAULO",
    "notes": "Setor: ADM | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 89,
    "equipmentId": "EQ10098",
    "name": "COMPUTADOR DELL",
    "category": "desktop",
    "model": "VOSTRO",
    "serialNumber": 35660632863,
    "status": "assigned",
    "location": "FAZENDA CATUAI",
    "assignedTo": "JOSE",
    "notes": "Setor: PCM | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 90,
    "equipmentId": "EQ10099",
    "name": "MONITOR NOC",
    "category": "monitor",
    "model": "E970WNI",
    "serialNumber": "T8IWV42QALAUNNB",
    "status": "assigned",
    "location": "FAZENDA CATUAI",
    "assignedTo": "JOSE",
    "notes": "Setor: PCM | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 91,
    "equipmentId": "EQ10100",
    "name": "NOTEBOOK VAIO",
    "category": "notebook",
    "model": "VJFE42F11X",
    "serialNumber": "89441416H",
    "status": "assigned",
    "location": "Fazenda Cabeceiras - PI",
    "assignedTo": "Jocelio Cordeiro",
    "notes": "Acessórios: FONTE ALIMENTACAO | Obs: I5-1021U/8GB"
  },
  {
    "id": 92,
    "equipmentId": "EQ10102",
    "name": "ALL IN ONE DELL",
    "category": "desktop",
    "model": "W12C",
    "serialNumber": "W12C006",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "LINALVA",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTCAO | Obs: I5-7200U/8GB"
  },
  {
    "id": 93,
    "equipmentId": "EQ10103",
    "name": "MONITOR DELL",
    "category": "monitor",
    "model": "E1914HC",
    "serialNumber": "BR-OFCFDPK-07591-442-WUXM",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "MARCOS",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 94,
    "equipmentId": "EQ10104",
    "name": "MINI PC DELL ",
    "category": "desktop",
    "model": "VOSTRO",
    "serialNumber": "BQFPX63",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "MARCOS",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTACAO | Obs: I5-9400/8GB"
  },
  {
    "id": 95,
    "equipmentId": "EQ10105",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "FE14",
    "serialNumber": "89423193D",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "GILMAR",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTACAO | Obs: I5-10210U/8GB"
  },
  {
    "id": 96,
    "equipmentId": "EQ10106",
    "name": "MONITOR LG",
    "category": "monitor",
    "model": 10106,
    "serialNumber": "E97OSWNL",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "GILMAR",
    "notes": "Setor: COMPRAS | Acessórios: FONTEALIMETACAOA"
  },
  {
    "id": 97,
    "equipmentId": "EQ10107",
    "name": "MONITOR DELL",
    "category": "monitor",
    "model": "E2222HS",
    "serialNumber": "BR-04VR-43-TUB00-239-107U-1O0",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RUDY",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 98,
    "equipmentId": "EQ10108",
    "name": "MONITOR ACER",
    "category": "monitor",
    "model": "6185HY",
    "serialNumber": "ETLPCODOO2131049728504",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RUDY",
    "notes": "Setor: COMPRAS  | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 99,
    "equipmentId": "EQ10109",
    "name": "PC DELL VOSTRO ",
    "category": "desktop",
    "model": "VOSTRO 3470",
    "serialNumber": "JBZP63",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "RUDY",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTACAO  | Obs: I5-9400/ 8GB"
  },
  {
    "id": 100,
    "equipmentId": "EQ10110",
    "name": "MONITOR LG",
    "category": "monitor",
    "model": "24MK430H-B",
    "serialNumber": "21AZKA90101",
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "BRUNO ",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 101,
    "equipmentId": "EQ10111",
    "name": "NB VAIO FE15",
    "category": "notebook",
    "model": "VAIO FE15",
    "serialNumber": 893606760,
    "status": "assigned",
    "location": "Matriz",
    "assignedTo": "BRUNO ",
    "notes": "Setor: COMPRAS | Acessórios: FONTE ALIMENTACAO | Obs: I7-106567/8G"
  },
  {
    "id": 102,
    "equipmentId": "EQ10112",
    "name": "TELEVISÃO LG ",
    "category": "other",
    "model": "9L2L0040",
    "serialNumber": "911AZMG4U731",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "PRODUCAO",
    "notes": "Setor: PRODUCAO"
  },
  {
    "id": 103,
    "equipmentId": "EQ10113",
    "name": "NB DELL",
    "category": "notebook",
    "model": "QCNFA335",
    "serialNumber": 11347007366,
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "ADRIANO",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1021U/8GB"
  },
  {
    "id": 104,
    "equipmentId": "EQ10114",
    "name": "NB DELL",
    "category": "notebook",
    "model": "TTYFJA00",
    "serialNumber": 18160270418,
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "CIRINEU",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1021U/8GB"
  },
  {
    "id": 105,
    "equipmentId": "EQ10115",
    "name": "MONITOR LG",
    "category": "monitor",
    "model": "24TL520S",
    "serialNumber": "908AZMGCV931",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "LUCIANA ",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 106,
    "equipmentId": "EQ10116",
    "name": "COMPUTADOR ",
    "category": "other",
    "model": 451414511,
    "serialNumber": 46142768,
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "LUCIANA ",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 107,
    "equipmentId": "EQ10117",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "9462NGW",
    "serialNumber": 894231430,
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "GABRIEL",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1021U/16GB"
  },
  {
    "id": 108,
    "equipmentId": "EQ10118",
    "name": "NB VAIO ",
    "category": "notebook",
    "model": "9462NGW",
    "serialNumber": "89383354W",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "LUCIANA ",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO TECLADO E MOUSE SEM FIO | Obs: I5-1021U/8GB"
  },
  {
    "id": 109,
    "equipmentId": "EQ10119",
    "name": "MONITOR ACER",
    "category": "monitor",
    "model": "WV6AAB04 ",
    "serialNumber": 83005367742,
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "BALANÇA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 110,
    "equipmentId": "EQ10120",
    "name": "MONITOR ACER",
    "category": "monitor",
    "model": "WV6AAB04 ",
    "serialNumber": 83005367742,
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "BALANÇA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 111,
    "equipmentId": "EQ10121",
    "name": "COMPUTADOR VINK",
    "category": "other",
    "model": "VINK",
    "serialNumber": "FNS",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "BALANÇA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 112,
    "equipmentId": "EQ10122",
    "name": "COMPUTADOR LG",
    "category": "other",
    "model": "LG",
    "serialNumber": "FNS",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "BALANÇA",
    "notes": "Setor: PRODUCAO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 113,
    "equipmentId": "EQ10123",
    "name": "NB ACER ",
    "category": "notebook",
    "model": "N20C5",
    "serialNumber": "NXK02AL005243DA6289501",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "JOSE NETO",
    "notes": "Setor: ALMOXERIFADO | Acessórios: FONTE ALIMENTACAO E MOUSE SEM FIO | Obs: I5-1021U/8GB"
  },
  {
    "id": 114,
    "equipmentId": "EQ10124",
    "name": "MONITOR LG",
    "category": "monitor",
    "model": "20MK400H-B",
    "serialNumber": "104SPPS0C176",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "JOSE NETO",
    "notes": "Setor: ALMOXERIFADO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 115,
    "equipmentId": "EQ10125",
    "name": "COMPUTADOR DELL",
    "category": "desktop",
    "model": "VOSTRO",
    "serialNumber": "VOSTRO 3681",
    "status": "assigned",
    "location": "FAZENDA NOSSA SENHORA",
    "assignedTo": "JOSE NETO",
    "notes": "Setor: ALMOXERIFADO | Acessórios: FONTE ALIMENTACAO"
  },
  {
    "id": 116,
    "equipmentId": "EQ10127",
    "name": "IPHONE XR VERMELHO",
    "category": "mobile",
    "model": "XR",
    "serialNumber": "C6KY15D7KXKQ",
    "status": "available",
    "location": "Local não informado",
    "assignedTo": null,
    "notes": "Setor: Produção | Obs: IMEI: 353059102667333/353059102594396"
  },
  {
    "id": 117,
    "equipmentId": "EQ10129",
    "name": "NOTEBOOK DELL",
    "category": "notebook",
    "model": "Inspiron 15 5566",
    "serialNumber": "3KBQ0L2",
    "status": "assigned",
    "location": "ESCRITORIO",
    "assignedTo": "RENATO ROGERIO",
    "notes": "Setor: COMPRAS | Acessórios: FONTE DE ALIMENTAÇÃO"
  },
  {
    "id": 118,
    "equipmentId": "EQ10130",
    "name": "NOTEBOOK VAIO",
    "category": "notebook",
    "model": "Modelo não informado",
    "serialNumber": "S/N",
    "status": "available",
    "location": "Local não informado",
    "assignedTo": null,
    "notes": null
  },
  {
    "id": 119,
    "equipmentId": "EQ10132",
    "name": "CELULAR MOTOROLA E22",
    "category": "mobile",
    "model": "PAVU0007BR",
    "serialNumber": "SVN8D83614",
    "status": "assigned",
    "location": "Escritorio ",
    "assignedTo": "Tina ",
    "notes": "Setor: Comercial | Acessórios: CARREGADOR, CABO USB, CHAVE REMOÇÃO CHIP | Obs: IMEI:355165987139757/355165987139765"
  },
  {
    "id": 120,
    "equipmentId": "EQ10137",
    "name": "IPHONE XR BRANCO",
    "category": "mobile",
    "model": "XR",
    "serialNumber": "G0NZ216NKXKP",
    "status": "available",
    "location": "Local não informado",
    "assignedTo": null,
    "notes": "Setor: Produção | Obs: IMEI: 356424107432983/356424107053524"
  },
  {
    "id": 121,
    "equipmentId": "EQ10138",
    "name": "IPHONE XR BRANCO",
    "category": "mobile",
    "model": "XR",
    "serialNumber": "F2LXRM0QKXKP",
    "status": "available",
    "location": "Local não informado",
    "assignedTo": null,
    "notes": "Setor: Produção | Obs: IMEI: 357343093088973/357343093275298"
  },
  {
    "id": 122,
    "equipmentId": "EQ10139",
    "name": "IPHONE XR BRANCO",
    "category": "mobile",
    "model": "XR",
    "serialNumber": "DNPXRQE3KXKP",
    "status": "available",
    "location": "Local não informado",
    "assignedTo": null,
    "notes": "Setor: Produção | Obs: IMEI: 357343095738442/357343095451319"
  },
  {
    "id": 123,
    "equipmentId": "EQ10145",
    "name": "DESKTOP DELL ",
    "category": "desktop",
    "model": "VOSTRO 3611",
    "serialNumber": "JDRF4F3",
    "status": "available",
    "location": "FAZ. CATUAI",
    "assignedTo": null,
    "notes": "Setor: FAZ. CATUAI | Acessórios: MONITOR, MOUSE E TECLADO"
  },
  {
    "id": 124,
    "equipmentId": "EQ10146",
    "name": "MONITOR AOC",
    "category": "monitor",
    "model": "AOC E970SWNL",
    "serialNumber": "HND63IA004759",
    "status": "available",
    "location": "FAZ. CATUAI",
    "assignedTo": null,
    "notes": "Setor: FAZ. CATUAI"
  }
];

// Replace the sample data with imported data
equipment = importedEquipment;
